### ISSUE TITLE
死锁问题

### ISSUE THREAD

**Issue by SillyFlame** [xia-chu/ZLMediaKit#486]
并发调用openRtpServer closeRtpServer会出现死锁。

```bash
(gdb) thread 6
[Switching to thread 6 (Thread 0x7f2ebd5e5700 (LWP **10783**))]
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135     ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) bt
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f2ec025042e in __GI___pthread_mutex_lock (mutex=0x1b78e48) at ../nptl/pthread_mutex_lock.c:115
**#2  0x0000000000525137 in mediakit::RtpSelector::getProcess(std::string const&, bool) ()
#3  0x000000000052684b in mediakit::RtpServer::start(unsigned short, std::string const&, bool, char const*) ()**
#4  0x0000000000475629 in <lambda(toolkit::SockInfo&, mediakit::HttpSession::KeyValue&, mediakit::HttpSession::KeyValue&, ApiArgsType&, Json::Value&)>::operator() (
    __closure=<optimized out>, headerIn=..., headerOut=..., val=..., allArgs=..., sender=...) at baidu/third-party/ZLMediaKit/3rdpart/ZLToolKit/src/Util/mini.h:148
#5  <lambda(toolkit::SockInfo&, mediakit::HttpSession::KeyValue&, mediakit::HttpSession::KeyValue&, ApiArgsType&, Json::Value&, const HttpResponseInvoker&)>::operator()
    (this=<optimized out>, headerIn=..., invoker=..., val=..., allArgs=..., headerOut=..., sender=...) at baidu/third-party/ZLMediaKit/server/WebApi.cpp:111
#6  std::_Function_handler<void(toolkit::SockInfo&, mediakit::StrCaseMap&, mediakit::StrCaseMap&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, toolkit::variant, mediakit::StrCaseCompare, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, toolkit::variant> > >&, Json::Value&, const mediakit::HttpResponseInvokerImp&), api_regist1(const string&, FUNC&&) [with FUNC = installWebApi()::<lambda(toolkit::SockInfo&, mediakit::HttpSession::KeyValue&, mediakit::HttpSession::KeyValue&, ApiArgsType&, Json::Value&)>; std::string = std::basic_string<char>]::<lambda(toolkit::SockInfo&, mediakit::HttpSession::KeyValue&, mediakit::HttpSession::KeyValue&, ApiArgsType&, Json::Value&, const HttpResponseInvoker&)> >::_M_invoke(const std::_Any_data &, toolkit::SockInfo &, mediakit::StrCaseMap &, mediakit::StrCaseMap &, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, toolkit::variant, mediakit::StrCaseCompare, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, toolkit::variant> > > &, Json::Value &, const mediakit::HttpResponseInvokerImp &) (__functor=..., __args#0=..., __args#1=..., __args#2=..., __args#3=..., __args#4=..., __args#5=...)
    at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/bits/std_function.h:297
#7  0x0000000000479bfc in std::function<void (toolkit::SockInfo&, mediakit::StrCaseMap&, mediakit::StrCaseMap&, std::map<std::string, toolkit::variant, mediakit::StrCaseCompare, std::allocator<std::pair<std::string const, toolkit::variant> > >&, Json::Value&, mediakit::HttpResponseInvokerImp const&)>::operator()(toolkit::SockInfo&, mediakit::StrCaseMap&, mediakit::StrCaseMap&, std::map<std::string, toolkit::variant, mediakit::StrCaseCompare, std::allocator<std::pair<std::string const, toolkit::variant> > >&, Json::Value&, mediakit::HttpResponseInvokerImp const&) const (__args#5=..., __args#4=..., __args#3=..., __args#2=..., __args#1=..., __args#0=..., this=0x1b58c08)
    at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/bits/std_function.h:682
#8  <lambda(const mediakit::Parser&, const HttpResponseInvoker&, bool&, toolkit::SockInfo&)>::operator()(const mediakit::Parser &, const mediakit::HttpSession::HttpResponseInvoker &, bool &, toolkit::SockInfo &) (parser=..., invoker=..., consumed=<optimized out>, sender=..., __closure=<optimized out>)
    at baidu/third-party/ZLMediaKit/server/WebApi.cpp:206
#9  0x00000000004d9f03 in mediakit::HttpSession::emitHttpEvent(bool) ()
#10 0x00000000004de699 in mediakit::HttpSession::Handle_Req_GET_l(long&, bool) ()
#11 0x00000000004dd19a in mediakit::HttpSession::onRecvHeader(char const*, unsigned long) ()
#12 0x00000000004d42b2 in mediakit::HttpRequestSplitter::input(char const*, unsigned long) ()
#13 0x00000000004914ec in toolkit::TcpServer::onAcceptConnection(std::shared_ptr<toolkit::Socket> const&)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) const (buf=..., __closure=<optimized out>)
    at baidu/third-party/ZLMediaKit/3rdpart/ZLToolKit/src/Network/TcpServer.h:244
#14 std::_Function_handler<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int), toolkit::TcpServer::onAcceptConnection(std::shared_ptr<toolkit::Socket> const&)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*&&, int&&) (
    __functor=..., __args#0=..., __args#1=<optimized out>, __args#2=<optimized out>) at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/bits/std_function.h:297
#15 0x00000000005ec3a8 in toolkit::Socket::onRead(std::shared_ptr<toolkit::SockFD> const&, bool) ()
#16 0x00000000005eef7f in std::_Function_handler<void (int), toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#17 0x00000000005fdb51 in toolkit::EventPoller::runLoop(bool, bool) ()
#18 0x00007f2ec017a16f in ?? () from /opt/compiler/gcc-8.2/lib/libstdc++.so.6
#19 0x00007f2ec024dda4 in start_thread (arg=<optimized out>) at pthread_create.c:333
#20 0x00007f2ebfedb32d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) f 1
#1  0x00007f2ec025042e in __GI___pthread_mutex_lock (mutex=0x1b78e48) at ../nptl/pthread_mutex_lock.c:115
115     ../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) p *mutex
$1 = {__data = {__lock = 2, __count = 1, __owner = **10784**, __nusers = 1, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
  __size = "\002\000\000\000\001\000\000\000 *\000\000\001\000\000\000\001", '\000' <repeats 22 times>, __align = 4294967298}
(gdb) thread 7
[Switching to thread 7 (Thread 0x7f2ebcbe4700 (LWP **10784**))]
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135     ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) bt
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f2ec025042e in __GI___pthread_mutex_lock (mutex=0x92e0c0 <s_rtpServerMapMtx>) at ../nptl/pthread_mutex_lock.c:115
#2  0x0000000000472368 in __gthread_mutex_lock (__mutex=0x92e0c0 <s_rtpServerMapMtx>)
    at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/x86_64-pc-linux-gnu/bits/gthr-default.h:748
#3  __gthread_recursive_mutex_lock (__mutex=0x92e0c0 <s_rtpServerMapMtx>)
    at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/x86_64-pc-linux-gnu/bits/gthr-default.h:810
#4  std::recursive_mutex::lock (this=0x92e0c0 <s_rtpServerMapMtx>) at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/mutex:107
#5  std::lock_guard<std::recursive_mutex>::lock_guard (__m=..., this=<synthetic pointer>) at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/bits/std_mutex.h:162
#6  <lambda(toolkit::SockInfo&, mediakit::HttpSession::KeyValue&, mediakit::HttpSession::KeyValue&, ApiArgsType&, Json::Value&)>::<lambda()>::operator() (
    __closure=0x9926d58) at baidu/third-party/ZLMediaKit/server/WebApi.cpp:781
#7  std::_Function_handler<void(), installWebApi()::<lambda(toolkit::SockInfo&, mediakit::HttpSession::KeyValue&, mediakit::HttpSession::KeyValue&, ApiArgsType&, Json::Value&)>::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /home/opt/compiler/gcc-8.2/gcc-8.2/include/c++/8.2.0/bits/std_function.h:297
#8  0x0000000000524bb0 in mediakit::RtpSelector::onManager() ()
#9  0x0000000000524d2d in std::_Function_handler<bool (), mediakit::RtpSelector::createTimer()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#10 0x0000000000600608 in std::_Function_handler<unsigned long (), toolkit::Timer::Timer(float, std::function<bool ()> const&, std::shared_ptr<toolkit::EventPoller> const&, bool)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#11 0x00000000005fd094 in toolkit::EventPoller::flushDelayTask(unsigned long) ()
#12 0x00000000005fd6a9 in toolkit::EventPoller::runLoop(bool, bool) ()
#13 0x00007f2ec017a16f in ?? () from /opt/compiler/gcc-8.2/lib/libstdc++.so.6
#14 0x00007f2ec024dda4 in start_thread (arg=<optimized out>) at pthread_create.c:333
#15 0x00007f2ebfedb32d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) f 1
#1  0x00007f2ec025042e in __GI___pthread_mutex_lock (mutex=0x92e0c0 <s_rtpServerMapMtx>) at ../nptl/pthread_mutex_lock.c:115
115     ../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) p *mutex
$2 = {__data = {__lock = 2, __count = 1, __owner = **10783**, __nusers = 1, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
  __size = "\002\000\000\000\001\000\000\000\037*\000\000\001\000\000\000\001", '\000' <repeats 22 times>, __align = 4294967298}
(gdb) 
```

**Comment by xia-chu** [comment]
```patch
Index: src/Rtp/RtpSelector.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtp/RtpSelector.cpp	(revision 07ef417250a7786ee6b774a3dcea34d195085749)
+++ src/Rtp/RtpSelector.cpp	(revision 100af97d51c1f254e67d28c1ea6ad889f8e86f77)
@@ -72,31 +72,40 @@
 }
 
 void RtpSelector::delProcess(const string &stream_id,const RtpProcess *ptr) {
-    lock_guard<decltype(_mtx_map)> lck(_mtx_map);
-    auto it = _map_rtp_process.find(stream_id);
-    if (it == _map_rtp_process.end()) {
-        return;
-    }
-    if (it->second->getProcess().get() != ptr) {
-        return;
-    }
-    auto process = it->second->getProcess();
-    _map_rtp_process.erase(it);
+    RtpProcess::Ptr process;
+    {
+        lock_guard<decltype(_mtx_map)> lck(_mtx_map);
+        auto it = _map_rtp_process.find(stream_id);
+        if (it == _map_rtp_process.end()) {
+            return;
+        }
+        if (it->second->getProcess().get() != ptr) {
+            return;
+        }
+        process = it->second->getProcess();
+        _map_rtp_process.erase(it);
+    }
     process->onDetach();
 }
 
 void RtpSelector::onManager() {
-    lock_guard<decltype(_mtx_map)> lck(_mtx_map);
-    for (auto it = _map_rtp_process.begin(); it != _map_rtp_process.end();) {
-        if (it->second->getProcess()->alive()) {
-            ++it;
-            continue;
-        }
-        WarnL << "RtpProcess timeout:" << it->first;
-        auto process = it->second->getProcess();
-        it = _map_rtp_process.erase(it);
+    List<RtpProcess::Ptr> clear_list;
+    {
+        lock_guard<decltype(_mtx_map)> lck(_mtx_map);
+        for (auto it = _map_rtp_process.begin(); it != _map_rtp_process.end();) {
+            if (it->second->getProcess()->alive()) {
+                ++it;
+                continue;
+            }
+            WarnL << "RtpProcess timeout:" << it->first;
+            clear_list.emplace_back(it->second->getProcess());
+            it = _map_rtp_process.erase(it);
+        }
+    }
+
+    clear_list.for_each([](const RtpProcess::Ptr &process) {
         process->onDetach();
-    }
+    });
 }
 
 RtpSelector::RtpSelector() {

```

**Comment by xia-chu** [comment]
请打上补丁 应该修复了

**Comment by SillyFlame** [comment]
打上补丁，跑了一段时间了，没有复现

**Comment by xia-chu** [comment]
issue先关闭，有问题请在此回复
