### ISSUE TITLE
flushDelayTask导致程序异常退出

### ISSUE THREAD

**Issue by ChuLiqiang** [xia-chu/ZLMediaKit#684]
```c++
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /home/Melineye_Server/Library/libz.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/b9/d5f73428bd6ad68c96986b57bea3b7cedb9745.debug
Core was generated by `./MediaServer -l 3 --daemon'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f4c51c1a0f8 in ?? () from /lib64/libgcc_s.so.1
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64                     libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 openssl-libs-1.0.2k-21.e                    l7_9.x86_64 pcre-8.32-17.el7.x86_64
(gdb) bt
#0  0x00007f4c51c1a0f8 in ?? () from /lib64/libgcc_s.so.1
#1  0x00007f4c51c1aff9 in _Unwind_Backtrace () from /lib64/libgcc_s.so.1
#2  0x00007f4c51951f16 in backtrace () from /lib64/libc.so.6
#3  0x0000000000529d71 in sig_crash(int) ()
#4  <signal handler called>
#5  0xffffffffffffffff in ?? ()
#6  0x0000000000590f30 in std::_Function_handler<unsigned long (), mediakit::findAsync_l(mediakit::MediaInfo const&, std::shared_ptr<toolkit::                    TcpSession> const&, bool, std::function<void (std::shared_ptr<mediakit::MediaSource> const&)> const&)::{lambda()#2}>::_M_invoke(std::_Any_data                     const&) ()
#7  0x00000000006db1e2 in toolkit::EventPoller::flushDelayTask(unsigned long) ()
#8  0x00000000006dbade in toolkit::EventPoller::runLoop(bool, bool) ()
#9  0x00007f4c521d8330 in ?? () from /lib64/libstdc++.so.6
#10 0x00007f4c52432dd5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f4c5193bead in clone () from /lib64/libc.so.6
```

**Comment by xia-chu** [comment]
是否修改过代码？

**Comment by ChuLiqiang** [comment]
> 是否修改过代码？
没改过.

**Comment by ChuLiqiang** [comment]
![image](https://user-images.githubusercontent.com/2747722/104185620-2c2a0400-5450-11eb-8724-1df8f0e5d0f2.png)
麻烦咨询一下,这块为啥要交换数据?

**Comment by xia-chu** [comment]
交互数据的目的是防止 在定时中增加删除定时器 相当于遍历map时 再增删元素
